### ISSUE TITLE
Enlazar todo el flujo de usuario

### ISSUE THREAD

**Issue by rbnmf** [AWS2/djmatrics#11]
- [x] Login (social login incluído)
- [x] Wizard de perfil de requerimientos
  - [x]  En el wizard, a partir de las selecciones hechas allí, se calcula el precio de la matrícula en base al algoritmo.
- [x] Validación de datos personales. Mostrar los datos de la matrícula, y ofrecer la opción de decir que todo ok, o solicitar a Secretaría que se cambie. Si se da OK, se muestra el dashboard
- [x] Muestra del dashboard, con semáforo y sacando los datos de la base de datos

**Comment by edusnchezj** [comment]
### Validación de datos personales [4H]

- [x] El usuario puede observar los datos en su pantalla. [2H] @edusnchezj 
- [x] El usuario si le da clic al botón de canviar dades se le mostrará un model para poder recibir información de cómo hacerlo. [2H] @edusnchezj

**Comment by edusnchezj** [comment]
### Login (social login incluído) [2H]

- [x] Redirección del usuario cuando inicia sesión. @edusnchezj 
   - [x] Cuando el usuario inicia sesión, se debe de saber si el usuario accede primero al wizard o no. Si no, será enviado a la dashboard. @edusnchezj 
- [x] El usuario no puede entrar a la pantalla de iniciar sesión si ha iniciado sesión. @edusnchezj 
- [x] El apartado de que se muestra el rol, el usuario/nombre y logout, no se debe de mostrar si el usuario no se ha logueado. @edusnchezj

**Comment by edusnchezj** [comment]
### Wizard del perfil de requerimientos [4H]

- [x] Realizar el wizard. @edusnchezj 
- [x] Conexión a la base de datos una vez que el usuario finaliza el wireframe. @edusnchezj 
- [x] Realizar el diseño de la selección de UFs. @edusnchezj [3H]
- [x] Diseñar la lógica del calculo de matricula. @PMartinOnTheCloud [3H]
- [x] Implementación del diseño con la lógica [1H] @edusnchezj @PMartinOnTheCloud
